### ISSUE TITLE
ImageMagick runtime

### ISSUE THREAD

**Issue by hoffergg** [hoffergg/s3-lambda-thumbnail#1]
Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can't be found at ChildProcess.<anonymous> (/var/task/node_modules/gm/lib/command.js:232:12) at ChildProcess.emit (events.js:198:13) at ChildProcess.EventEmitter.emit (domain.js:448:20) at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12) at onErrorNT (internal/child_process.js:415:16) at process._tickCallback (internal/process/next_tick.js:63:19) 'Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can\'t be found\n at ChildProcess.<anonymous> (/var/task/node_modules/gm/lib/command.js:232:12)\n at ChildProcess.emit (events.js:198:13)\n at ChildProcess.EventEmitter.emit (domain.js:448:20)\n at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)\n at onErrorNT (internal/child_process.js:415:16)\n at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by hoffergg** [comment]
Add image-magick-lambda-layer as a layer to function.

click https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:145266761615:applications~image-magick-lambda-layer
